server:
  port: 8080

solon.app:
  name: chat

# 以下为默认值，可以都不加，或者想改哪行加哪行(支持"云端配置服务"进行配置，支持写到"云端日志服务")
solon:
  logging:
    appender:
      console:
        level: TRACE
      file:
        name: "logs/${solon.app.name}"
        level: INFO
        maxFileSize: "10 MB"
        maxHistory: "7"
      cloud:
        level: INFO
    logger:
      "root": #默认记录器配置
        level: TRACE
      "com.zaxxer.hikari":
        level: WARN

